apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: finish-graphs.softwareengineering.solvinity.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: softwareengineering.solvinity.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources: { status: {} }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                protected:
                  type: boolean
                databases:
                  type: array
                  items:
                    type: object
                    properties:
                      Start: # for monitoring purposes
                        type: string
                        pattern: "^[0-9a-z-./]+$"
                        maxLength: 32
                        description: Name of the start CRD object
                      SubNamespace:
                        type: string
                        pattern: "^[0-9a-z-./]+$"
                        maxLength: 32
                        description: Name of the sub namespace
                      UserEmail:
                        type: string
                        maxLength: 128
                        description: user email to be notified
                      ResultCode:
                        type: integer
                        description: Http like result code
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

  scope: Namespaced
  names:
    plural: finish-graphs
    singular: finish-graph
    kind: finish-g
    shortNames:
      - fh-g
      - finish
