apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spinupcontainers
rules:
  - apiGroups: ["", "*"]
    resources: ["*"]
    verbs:
      - create
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spinupcontainers
  namespace: serverless-graphs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spinupcontainers
subjects:
  - kind: ServiceAccount
    name: spinupcontainers
    namespace: serverless-graphs
roleRef:
  kind: ClusterRole
  name: spinupcontainers
  apiGroup: rbac.authorization.k8s.io
