apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: serverless-graphs.softwareengineering.solvinity.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: softwareengineering.solvinity.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources: { status: {} }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                protected:
                  type: boolean
                databases:
                  type: array
                  items:
                    type: object
                    properties:
                      Tenant: # for monitoring purposes
                        type: string
                        pattern: "^[0-9a-z-./]+$"
                        maxLength: 32
                        description: Tenant that wants to run a graph
                      User:
                        type: string
                        pattern: "^[0-9a-z-./]+$"
                        maxLength: 32
                        description: user for the tanent
                      UserEmail:
                        type: string
                        maxLength: 128
                        description: user email to be notified
                      GraphLocation:
                        type: string
                        maxLength: 128
                        description: the location of the graph to be processed
                      NrWorkers:
                        type: integer
                        description: number of graph worker nodes
                        required:
                          - Tenant
                          - User
                          - TenantLocation
                          - GraphLocation
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

  scope: Namespaced
  names:
    plural: serverless-graphs
    singular: serverless-graph
    kind: serverless-g
    shortNames:
      - sl-g
      - start
